### ISSUE TITLE
 Cookie in js

### ISSUE THREAD

**Issue by annu12340** [annu12340/js#11]
What are cookie, how can we access them using js, how to create a Cookie using JavaScript etc

**Comment by vedanttttt** [comment]
Please assign this issue to me .

**Comment by annu12340** [comment]
Hey @vedanttttt :wave:

**Comment by vedanttttt** [comment]
> Hey @vedanttttt 👋

Hey , Thanks

**Comment by annu12340** [comment]
Solved
