### ISSUE TITLE
Topics on errors and error handling are missing

### ISSUE THREAD

**Issue by annu12340** [annu12340/js#2]
Topics like different types of errors (runtime, logical, compile error) and error handling (try..catch) are missing

**Comment by araut1** [comment]
Hey, can I have this one?

**Comment by annu12340** [comment]
Yeah sure @araut1 :)

**Comment by araut1** [comment]
Hi Annu, could you please provide me write access to the repo?

**Comment by araut1** [comment]
Hey, I made a PULL request. Let me know if you find any issues. Thanks. Keep Building!

**Comment by annu12340** [comment]
Solved
