### ISSUE TITLE
Add hacktoberfest label to your repo

### ISSUE THREAD

**Issue by Vrindagupta6828** [annu12340/js#34]

**Comment by Vrindagupta6828** [comment]
@annu12340  Please add hacktoberfest label to your repo and mark my issue that is adding generator function as hacktoberfest accepted in order for it to count as the guidelines have changed.

**Comment by annu12340** [comment]
Hey @Vrindagupta6828 
```
PRs count if:
Submitted during the month of October AND
Submitted in a public repo AND (
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  Submitted in a repo with the hacktoberfest topic AND (
    The PR is merged OR
    The PR has been approved
  )
)
```
Since I had labelled the issue that you solved as ```hacktoberfest ``` and it was merged, I think that would be sufficient

Anyways, I am also adding ```hacktoberfest accepted ``` label to your pr  😄

**Comment by Vrindagupta6828** [comment]
@annu12340 thnx
