### ISSUE TITLE
Difference between Attributes and Property?

### ISSUE THREAD

**Issue by annu12340** [annu12340/js#4]
Briefly explain the difference between Attributes and Property

**Comment by Jaideep07** [comment]
I would like to do this, can you tell me where to write exactly.

**Comment by annu12340** [comment]
Hey @Jaideep07  thanks for commenting

In https://github.com/annu12340/Javascript-Notes/tree/master/docs
you can add it in the 'beginner' section

**Comment by annu12340** [comment]
Solved
