### ISSUE TITLE
Difference between Local storage & Session storage

### ISSUE THREAD

**Issue by annu12340** [annu12340/js#5]
Explain briefly what is the difference between Local storage & Session storage

**Comment by kryptocodes** [comment]
## LocalStorage

The Local Storage is a type of storage which accessible on all windows in the browser. When it comes to the storage capacity, it can store upto 5–10 MB, which is much better. And the values set in local storage never expires until and unless we manually remove them.

##Session Storage

The Session Storage has a lot of similarities to Local Storage, but the storage size is limited to 5MB. Also, the values stored gets automatically removed from the browser when you close the active tab. As the name suggests, the values are only available for that session.

**Comment by priyanshupardhi** [comment]
Hi @annu12340 !
I'd like to work on this issue.
Under which section should I put it?

**Comment by annu12340** [comment]
Hey @priyanshupardhi 
Thanks for commenting :)

In https://github.com/annu12340/Javascript-Notes/tree/master/docs
you can add it in the 'advanced' section

**Comment by annu12340** [comment]
Solved
