### ISSUE TITLE
 Difference between innerHTML & innerText

### ISSUE THREAD

**Issue by annu12340** [annu12340/js#6]
What is the difference between innerHTML & innerText

**Comment by krishna16sharma** [comment]
Hi @annu12340 !
I'd like to work on this issue.
Under which section should I put it?

**Comment by priyanshupardhi** [comment]
@annu12340 I would like to contribute

**Comment by annu12340** [comment]
Hey @krishna16sharma and @priyanshupardhi thanks for commenting
Since @krishna16sharma responded first, I am assigning it to @krishna16sharma 

In https://github.com/annu12340/Javascript-Notes/tree/master/docs
you can add it in the 'beginner' section

**Comment by annu12340** [comment]
Solved
