### ISSUE TITLE
Generator functions

### ISSUE THREAD

**Issue by annu12340** [annu12340/js#9]
Briefly explain generator functions in js

**Comment by annu12340** [comment]
What is generator function and why do we use them

**Comment by Vrindagupta6828** [comment]
#annul12340 please assign me this. I want to work on this.

**Comment by annu12340** [comment]
Hey @Vrindagupta6828 :wave:

**Comment by Vrindagupta6828** [comment]
@annu12340  where i have to add this md file?

**Comment by Vrindagupta6828** [comment]
@annu12340  and this will be md file right?

**Comment by annu12340** [comment]
> @annu12340 where i have to add this md file?

You could add this under the 'advanced ' section after the <br/> tag (ie before Asynchronous js)

**Comment by annu12340** [comment]
> @annu12340 and this will be md file right?

Yes

**Comment by annu12340** [comment]
Solved
